/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TablesRouteImport } from './routes/tables'
import { Route as StockRouteImport } from './routes/stock'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as ReceiptPreviewRouteImport } from './routes/receipt-preview'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CurrenciesRouteImport } from './routes/currencies'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as ReportsRouteRouteImport } from './routes/reports/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as ShiftsIndexRouteImport } from './routes/shifts/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as PurchaseOrdersIndexRouteImport } from './routes/purchase-orders/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as OffersIndexRouteImport } from './routes/offers/index'
import { Route as ModifiersIndexRouteImport } from './routes/modifiers/index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices/index'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as SuppliersSupplierIdRouteImport } from './routes/suppliers/$supplierId'
import { Route as StaffStaffIdRouteImport } from './routes/staff/$staffId'
import { Route as SettingsUpdateRouteImport } from './routes/settings/update'
import { Route as SettingsThemesRouteImport } from './routes/settings/themes'
import { Route as SettingsTenantRouteImport } from './routes/settings/tenant'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsLoyaltyRouteImport } from './routes/settings/loyalty'
import { Route as SettingsCurrenciesRouteImport } from './routes/settings/currencies'
import { Route as SettingsColorsRouteImport } from './routes/settings/colors'
import { Route as SettingsAboutRouteImport } from './routes/settings/about'
import { Route as ReportsSalesRouteImport } from './routes/reports/sales'
import { Route as ReportsProductsRouteImport } from './routes/reports/products'
import { Route as ReportsPaymentsRouteImport } from './routes/reports/payments'
import { Route as ReportsLoyaltyRouteImport } from './routes/reports/loyalty'
import { Route as ReportsInventoryRouteImport } from './routes/reports/inventory'
import { Route as ReportsFinancialsRouteImport } from './routes/reports/financials'
import { Route as ReportsDebtsRouteImport } from './routes/reports/debts'
import { Route as ReportsCustomersRouteImport } from './routes/reports/customers'
import { Route as PurchaseOrdersPurchaseOrderIdRouteImport } from './routes/purchase-orders/$purchaseOrderId'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as InvoicesOrderIdRouteImport } from './routes/invoices/$orderId'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers/$customerId'
import { Route as CategoriesCategoryIdRouteImport } from './routes/categories/$categoryId'

const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptPreviewRoute = ReceiptPreviewRouteImport.update({
  id: '/receipt-preview',
  path: '/receipt-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrenciesRoute = CurrenciesRouteImport.update({
  id: '/currencies',
  path: '/currencies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRouteRoute = ReportsRouteRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsIndexRoute = ShiftsIndexRouteImport.update({
  id: '/shifts/',
  path: '/shifts/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const PurchaseOrdersIndexRoute = PurchaseOrdersIndexRouteImport.update({
  id: '/purchase-orders/',
  path: '/purchase-orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersIndexRoute = OffersIndexRouteImport.update({
  id: '/offers/',
  path: '/offers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModifiersIndexRoute = ModifiersIndexRouteImport.update({
  id: '/modifiers/',
  path: '/modifiers/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersSupplierIdRoute = SuppliersSupplierIdRouteImport.update({
  id: '/suppliers/$supplierId',
  path: '/suppliers/$supplierId',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffStaffIdRoute = StaffStaffIdRouteImport.update({
  id: '/staff/$staffId',
  path: '/staff/$staffId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUpdateRoute = SettingsUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsThemesRoute = SettingsThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsTenantRoute = SettingsTenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsLoyaltyRoute = SettingsLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsCurrenciesRoute = SettingsCurrenciesRouteImport.update({
  id: '/currencies',
  path: '/currencies',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsColorsRoute = SettingsColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const ReportsSalesRoute = ReportsSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => ReportsRouteRoute,
} as any)
const ReportsProductsRoute = ReportsProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => ReportsRouteRoute,
} as any)
const ReportsPaymentsRoute = ReportsPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ReportsRouteRoute,
} as any)
const ReportsLoyaltyRoute = ReportsLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => ReportsRouteRoute,
} as any)
const ReportsInventoryRoute = ReportsInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => ReportsRouteRoute,
} as any)
const ReportsFinancialsRoute = ReportsFinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => ReportsRouteRoute,
} as any)
const ReportsDebtsRoute = ReportsDebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => ReportsRouteRoute,
} as any)
const ReportsCustomersRoute = ReportsCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => ReportsRouteRoute,
} as any)
const PurchaseOrdersPurchaseOrderIdRoute =
  PurchaseOrdersPurchaseOrderIdRouteImport.update({
    id: '/purchase-orders/$purchaseOrderId',
    path: '/purchase-orders/$purchaseOrderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesOrderIdRoute = InvoicesOrderIdRouteImport.update({
  id: '/invoices/$orderId',
  path: '/invoices/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryIdRoute = CategoriesCategoryIdRouteImport.update({
  id: '/categories/$categoryId',
  path: '/categories/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reports': typeof ReportsRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/currencies': typeof CurrenciesRoute
  '/dashboard': typeof DashboardRoute
  '/kitchen': typeof KitchenRoute
  '/payments': typeof PaymentsRoute
  '/receipt-preview': typeof ReceiptPreviewRoute
  '/refunds': typeof RefundsRoute
  '/stock': typeof StockRoute
  '/tables': typeof TablesRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/invoices/$orderId': typeof InvoicesOrderIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/purchase-orders/$purchaseOrderId': typeof PurchaseOrdersPurchaseOrderIdRoute
  '/reports/customers': typeof ReportsCustomersRoute
  '/reports/debts': typeof ReportsDebtsRoute
  '/reports/financials': typeof ReportsFinancialsRoute
  '/reports/inventory': typeof ReportsInventoryRoute
  '/reports/loyalty': typeof ReportsLoyaltyRoute
  '/reports/payments': typeof ReportsPaymentsRoute
  '/reports/products': typeof ReportsProductsRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/colors': typeof SettingsColorsRoute
  '/settings/currencies': typeof SettingsCurrenciesRoute
  '/settings/loyalty': typeof SettingsLoyaltyRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/tenant': typeof SettingsTenantRoute
  '/settings/themes': typeof SettingsThemesRoute
  '/settings/update': typeof SettingsUpdateRoute
  '/staff/$staffId': typeof StaffStaffIdRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRoute
  '/categories/': typeof CategoriesIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/modifiers/': typeof ModifiersIndexRoute
  '/offers/': typeof OffersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/purchase-orders/': typeof PurchaseOrdersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/shifts/': typeof ShiftsIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reports': typeof ReportsRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/currencies': typeof CurrenciesRoute
  '/dashboard': typeof DashboardRoute
  '/kitchen': typeof KitchenRoute
  '/payments': typeof PaymentsRoute
  '/receipt-preview': typeof ReceiptPreviewRoute
  '/refunds': typeof RefundsRoute
  '/stock': typeof StockRoute
  '/tables': typeof TablesRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/invoices/$orderId': typeof InvoicesOrderIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/purchase-orders/$purchaseOrderId': typeof PurchaseOrdersPurchaseOrderIdRoute
  '/reports/customers': typeof ReportsCustomersRoute
  '/reports/debts': typeof ReportsDebtsRoute
  '/reports/financials': typeof ReportsFinancialsRoute
  '/reports/inventory': typeof ReportsInventoryRoute
  '/reports/loyalty': typeof ReportsLoyaltyRoute
  '/reports/payments': typeof ReportsPaymentsRoute
  '/reports/products': typeof ReportsProductsRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/colors': typeof SettingsColorsRoute
  '/settings/currencies': typeof SettingsCurrenciesRoute
  '/settings/loyalty': typeof SettingsLoyaltyRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/tenant': typeof SettingsTenantRoute
  '/settings/themes': typeof SettingsThemesRoute
  '/settings/update': typeof SettingsUpdateRoute
  '/staff/$staffId': typeof StaffStaffIdRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRoute
  '/categories': typeof CategoriesIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/modifiers': typeof ModifiersIndexRoute
  '/offers': typeof OffersIndexRoute
  '/products': typeof ProductsIndexRoute
  '/purchase-orders': typeof PurchaseOrdersIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/shifts': typeof ShiftsIndexRoute
  '/staff': typeof StaffIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reports': typeof ReportsRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/currencies': typeof CurrenciesRoute
  '/dashboard': typeof DashboardRoute
  '/kitchen': typeof KitchenRoute
  '/payments': typeof PaymentsRoute
  '/receipt-preview': typeof ReceiptPreviewRoute
  '/refunds': typeof RefundsRoute
  '/stock': typeof StockRoute
  '/tables': typeof TablesRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/invoices/$orderId': typeof InvoicesOrderIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/purchase-orders/$purchaseOrderId': typeof PurchaseOrdersPurchaseOrderIdRoute
  '/reports/customers': typeof ReportsCustomersRoute
  '/reports/debts': typeof ReportsDebtsRoute
  '/reports/financials': typeof ReportsFinancialsRoute
  '/reports/inventory': typeof ReportsInventoryRoute
  '/reports/loyalty': typeof ReportsLoyaltyRoute
  '/reports/payments': typeof ReportsPaymentsRoute
  '/reports/products': typeof ReportsProductsRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/colors': typeof SettingsColorsRoute
  '/settings/currencies': typeof SettingsCurrenciesRoute
  '/settings/loyalty': typeof SettingsLoyaltyRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/tenant': typeof SettingsTenantRoute
  '/settings/themes': typeof SettingsThemesRoute
  '/settings/update': typeof SettingsUpdateRoute
  '/staff/$staffId': typeof StaffStaffIdRoute
  '/suppliers/$supplierId': typeof SuppliersSupplierIdRoute
  '/categories/': typeof CategoriesIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/modifiers/': typeof ModifiersIndexRoute
  '/offers/': typeof OffersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/purchase-orders/': typeof PurchaseOrdersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/shifts/': typeof ShiftsIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reports'
    | '/settings'
    | '/auth'
    | '/currencies'
    | '/dashboard'
    | '/kitchen'
    | '/payments'
    | '/receipt-preview'
    | '/refunds'
    | '/stock'
    | '/tables'
    | '/categories/$categoryId'
    | '/customers/$customerId'
    | '/invoices/$orderId'
    | '/products/$productId'
    | '/purchase-orders/$purchaseOrderId'
    | '/reports/customers'
    | '/reports/debts'
    | '/reports/financials'
    | '/reports/inventory'
    | '/reports/loyalty'
    | '/reports/payments'
    | '/reports/products'
    | '/reports/sales'
    | '/settings/about'
    | '/settings/colors'
    | '/settings/currencies'
    | '/settings/loyalty'
    | '/settings/profile'
    | '/settings/tenant'
    | '/settings/themes'
    | '/settings/update'
    | '/staff/$staffId'
    | '/suppliers/$supplierId'
    | '/categories/'
    | '/customers/'
    | '/invoices/'
    | '/modifiers/'
    | '/offers/'
    | '/products/'
    | '/purchase-orders/'
    | '/settings/'
    | '/shifts/'
    | '/staff/'
    | '/suppliers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reports'
    | '/auth'
    | '/currencies'
    | '/dashboard'
    | '/kitchen'
    | '/payments'
    | '/receipt-preview'
    | '/refunds'
    | '/stock'
    | '/tables'
    | '/categories/$categoryId'
    | '/customers/$customerId'
    | '/invoices/$orderId'
    | '/products/$productId'
    | '/purchase-orders/$purchaseOrderId'
    | '/reports/customers'
    | '/reports/debts'
    | '/reports/financials'
    | '/reports/inventory'
    | '/reports/loyalty'
    | '/reports/payments'
    | '/reports/products'
    | '/reports/sales'
    | '/settings/about'
    | '/settings/colors'
    | '/settings/currencies'
    | '/settings/loyalty'
    | '/settings/profile'
    | '/settings/tenant'
    | '/settings/themes'
    | '/settings/update'
    | '/staff/$staffId'
    | '/suppliers/$supplierId'
    | '/categories'
    | '/customers'
    | '/invoices'
    | '/modifiers'
    | '/offers'
    | '/products'
    | '/purchase-orders'
    | '/settings'
    | '/shifts'
    | '/staff'
    | '/suppliers'
  id:
    | '__root__'
    | '/'
    | '/reports'
    | '/settings'
    | '/auth'
    | '/currencies'
    | '/dashboard'
    | '/kitchen'
    | '/payments'
    | '/receipt-preview'
    | '/refunds'
    | '/stock'
    | '/tables'
    | '/categories/$categoryId'
    | '/customers/$customerId'
    | '/invoices/$orderId'
    | '/products/$productId'
    | '/purchase-orders/$purchaseOrderId'
    | '/reports/customers'
    | '/reports/debts'
    | '/reports/financials'
    | '/reports/inventory'
    | '/reports/loyalty'
    | '/reports/payments'
    | '/reports/products'
    | '/reports/sales'
    | '/settings/about'
    | '/settings/colors'
    | '/settings/currencies'
    | '/settings/loyalty'
    | '/settings/profile'
    | '/settings/tenant'
    | '/settings/themes'
    | '/settings/update'
    | '/staff/$staffId'
    | '/suppliers/$supplierId'
    | '/categories/'
    | '/customers/'
    | '/invoices/'
    | '/modifiers/'
    | '/offers/'
    | '/products/'
    | '/purchase-orders/'
    | '/settings/'
    | '/shifts/'
    | '/staff/'
    | '/suppliers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReportsRouteRoute: typeof ReportsRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CurrenciesRoute: typeof CurrenciesRoute
  DashboardRoute: typeof DashboardRoute
  KitchenRoute: typeof KitchenRoute
  PaymentsRoute: typeof PaymentsRoute
  ReceiptPreviewRoute: typeof ReceiptPreviewRoute
  RefundsRoute: typeof RefundsRoute
  StockRoute: typeof StockRoute
  TablesRoute: typeof TablesRoute
  CategoriesCategoryIdRoute: typeof CategoriesCategoryIdRoute
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  InvoicesOrderIdRoute: typeof InvoicesOrderIdRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  PurchaseOrdersPurchaseOrderIdRoute: typeof PurchaseOrdersPurchaseOrderIdRoute
  StaffStaffIdRoute: typeof StaffStaffIdRoute
  SuppliersSupplierIdRoute: typeof SuppliersSupplierIdRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
  ModifiersIndexRoute: typeof ModifiersIndexRoute
  OffersIndexRoute: typeof OffersIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  PurchaseOrdersIndexRoute: typeof PurchaseOrdersIndexRoute
  ShiftsIndexRoute: typeof ShiftsIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt-preview': {
      id: '/receipt-preview'
      path: '/receipt-preview'
      fullPath: '/receipt-preview'
      preLoaderRoute: typeof ReceiptPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currencies': {
      id: '/currencies'
      path: '/currencies'
      fullPath: '/currencies'
      preLoaderRoute: typeof CurrenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts/': {
      id: '/shifts/'
      path: '/shifts'
      fullPath: '/shifts/'
      preLoaderRoute: typeof ShiftsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/purchase-orders/': {
      id: '/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/purchase-orders/'
      preLoaderRoute: typeof PurchaseOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/': {
      id: '/offers/'
      path: '/offers'
      fullPath: '/offers/'
      preLoaderRoute: typeof OffersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modifiers/': {
      id: '/modifiers/'
      path: '/modifiers'
      fullPath: '/modifiers/'
      preLoaderRoute: typeof ModifiersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/$supplierId': {
      id: '/suppliers/$supplierId'
      path: '/suppliers/$supplierId'
      fullPath: '/suppliers/$supplierId'
      preLoaderRoute: typeof SuppliersSupplierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/$staffId': {
      id: '/staff/$staffId'
      path: '/staff/$staffId'
      fullPath: '/staff/$staffId'
      preLoaderRoute: typeof StaffStaffIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/update': {
      id: '/settings/update'
      path: '/update'
      fullPath: '/settings/update'
      preLoaderRoute: typeof SettingsUpdateRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/themes': {
      id: '/settings/themes'
      path: '/themes'
      fullPath: '/settings/themes'
      preLoaderRoute: typeof SettingsThemesRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/tenant': {
      id: '/settings/tenant'
      path: '/tenant'
      fullPath: '/settings/tenant'
      preLoaderRoute: typeof SettingsTenantRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/loyalty': {
      id: '/settings/loyalty'
      path: '/loyalty'
      fullPath: '/settings/loyalty'
      preLoaderRoute: typeof SettingsLoyaltyRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/currencies': {
      id: '/settings/currencies'
      path: '/currencies'
      fullPath: '/settings/currencies'
      preLoaderRoute: typeof SettingsCurrenciesRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/colors': {
      id: '/settings/colors'
      path: '/colors'
      fullPath: '/settings/colors'
      preLoaderRoute: typeof SettingsColorsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/reports/sales': {
      id: '/reports/sales'
      path: '/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof ReportsSalesRouteImport
      parentRoute: typeof ReportsRouteRoute
    }
    '/reports/products': {
      id: '/reports/products'
      path: '/products'
      fullPath: '/reports/products'
      preLoaderRoute: typeof ReportsProductsRouteImport
      parentRoute: typeof ReportsRouteRoute
    }
    '/reports/payments': {
      id: '/reports/payments'
      path: '/payments'
      fullPath: '/reports/payments'
      preLoaderRoute: typeof ReportsPaymentsRouteImport
      parentRoute: typeof ReportsRouteRoute
    }
    '/reports/loyalty': {
      id: '/reports/loyalty'
      path: '/loyalty'
      fullPath: '/reports/loyalty'
      preLoaderRoute: typeof ReportsLoyaltyRouteImport
      parentRoute: typeof ReportsRouteRoute
    }
    '/reports/inventory': {
      id: '/reports/inventory'
      path: '/inventory'
      fullPath: '/reports/inventory'
      preLoaderRoute: typeof ReportsInventoryRouteImport
      parentRoute: typeof ReportsRouteRoute
    }
    '/reports/financials': {
      id: '/reports/financials'
      path: '/financials'
      fullPath: '/reports/financials'
      preLoaderRoute: typeof ReportsFinancialsRouteImport
      parentRoute: typeof ReportsRouteRoute
    }
    '/reports/debts': {
      id: '/reports/debts'
      path: '/debts'
      fullPath: '/reports/debts'
      preLoaderRoute: typeof ReportsDebtsRouteImport
      parentRoute: typeof ReportsRouteRoute
    }
    '/reports/customers': {
      id: '/reports/customers'
      path: '/customers'
      fullPath: '/reports/customers'
      preLoaderRoute: typeof ReportsCustomersRouteImport
      parentRoute: typeof ReportsRouteRoute
    }
    '/purchase-orders/$purchaseOrderId': {
      id: '/purchase-orders/$purchaseOrderId'
      path: '/purchase-orders/$purchaseOrderId'
      fullPath: '/purchase-orders/$purchaseOrderId'
      preLoaderRoute: typeof PurchaseOrdersPurchaseOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$orderId': {
      id: '/invoices/$orderId'
      path: '/invoices/$orderId'
      fullPath: '/invoices/$orderId'
      preLoaderRoute: typeof InvoicesOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categoryId': {
      id: '/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof CategoriesCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReportsRouteRouteChildren {
  ReportsCustomersRoute: typeof ReportsCustomersRoute
  ReportsDebtsRoute: typeof ReportsDebtsRoute
  ReportsFinancialsRoute: typeof ReportsFinancialsRoute
  ReportsInventoryRoute: typeof ReportsInventoryRoute
  ReportsLoyaltyRoute: typeof ReportsLoyaltyRoute
  ReportsPaymentsRoute: typeof ReportsPaymentsRoute
  ReportsProductsRoute: typeof ReportsProductsRoute
  ReportsSalesRoute: typeof ReportsSalesRoute
}

const ReportsRouteRouteChildren: ReportsRouteRouteChildren = {
  ReportsCustomersRoute: ReportsCustomersRoute,
  ReportsDebtsRoute: ReportsDebtsRoute,
  ReportsFinancialsRoute: ReportsFinancialsRoute,
  ReportsInventoryRoute: ReportsInventoryRoute,
  ReportsLoyaltyRoute: ReportsLoyaltyRoute,
  ReportsPaymentsRoute: ReportsPaymentsRoute,
  ReportsProductsRoute: ReportsProductsRoute,
  ReportsSalesRoute: ReportsSalesRoute,
}

const ReportsRouteRouteWithChildren = ReportsRouteRoute._addFileChildren(
  ReportsRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsColorsRoute: typeof SettingsColorsRoute
  SettingsCurrenciesRoute: typeof SettingsCurrenciesRoute
  SettingsLoyaltyRoute: typeof SettingsLoyaltyRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsTenantRoute: typeof SettingsTenantRoute
  SettingsThemesRoute: typeof SettingsThemesRoute
  SettingsUpdateRoute: typeof SettingsUpdateRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsColorsRoute: SettingsColorsRoute,
  SettingsCurrenciesRoute: SettingsCurrenciesRoute,
  SettingsLoyaltyRoute: SettingsLoyaltyRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsTenantRoute: SettingsTenantRoute,
  SettingsThemesRoute: SettingsThemesRoute,
  SettingsUpdateRoute: SettingsUpdateRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReportsRouteRoute: ReportsRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CurrenciesRoute: CurrenciesRoute,
  DashboardRoute: DashboardRoute,
  KitchenRoute: KitchenRoute,
  PaymentsRoute: PaymentsRoute,
  ReceiptPreviewRoute: ReceiptPreviewRoute,
  RefundsRoute: RefundsRoute,
  StockRoute: StockRoute,
  TablesRoute: TablesRoute,
  CategoriesCategoryIdRoute: CategoriesCategoryIdRoute,
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  InvoicesOrderIdRoute: InvoicesOrderIdRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  PurchaseOrdersPurchaseOrderIdRoute: PurchaseOrdersPurchaseOrderIdRoute,
  StaffStaffIdRoute: StaffStaffIdRoute,
  SuppliersSupplierIdRoute: SuppliersSupplierIdRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
  ModifiersIndexRoute: ModifiersIndexRoute,
  OffersIndexRoute: OffersIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  PurchaseOrdersIndexRoute: PurchaseOrdersIndexRoute,
  ShiftsIndexRoute: ShiftsIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
