/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as TablesRouteImport } from './routes/tables'
import { Route as StockRouteImport } from './routes/stock'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ReportsRouteRouteImport } from './routes/reports/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices/index'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as ReportsSalesRouteImport } from './routes/reports/sales'
import { Route as ReportsProductsRouteImport } from './routes/reports/products'
import { Route as ReportsPaymentsRouteImport } from './routes/reports/payments'
import { Route as ReportsInventoryRouteImport } from './routes/reports/inventory'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers/$customerId'
import { Route as CategoriesCategoryIdRouteImport } from './routes/categories/$categoryId'

const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRouteRoute = ReportsRouteRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSalesRoute = ReportsSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => ReportsRouteRoute,
} as any)
const ReportsProductsRoute = ReportsProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => ReportsRouteRoute,
} as any)
const ReportsPaymentsRoute = ReportsPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ReportsRouteRoute,
} as any)
const ReportsInventoryRoute = ReportsInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => ReportsRouteRoute,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryIdRoute = CategoriesCategoryIdRouteImport.update({
  id: '/categories/$categoryId',
  path: '/categories/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reports': typeof ReportsRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/payments': typeof PaymentsRoute
  '/recipes': typeof RecipesRoute
  '/stock': typeof StockRoute
  '/tables': typeof TablesRoute
  '/transfers': typeof TransfersRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/reports/inventory': typeof ReportsInventoryRoute
  '/reports/payments': typeof ReportsPaymentsRoute
  '/reports/products': typeof ReportsProductsRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/categories': typeof CategoriesIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/products': typeof ProductsIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reports': typeof ReportsRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/payments': typeof PaymentsRoute
  '/recipes': typeof RecipesRoute
  '/stock': typeof StockRoute
  '/tables': typeof TablesRoute
  '/transfers': typeof TransfersRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/reports/inventory': typeof ReportsInventoryRoute
  '/reports/payments': typeof ReportsPaymentsRoute
  '/reports/products': typeof ReportsProductsRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/categories': typeof CategoriesIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/products': typeof ProductsIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reports': typeof ReportsRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/payments': typeof PaymentsRoute
  '/recipes': typeof RecipesRoute
  '/stock': typeof StockRoute
  '/tables': typeof TablesRoute
  '/transfers': typeof TransfersRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/reports/inventory': typeof ReportsInventoryRoute
  '/reports/payments': typeof ReportsPaymentsRoute
  '/reports/products': typeof ReportsProductsRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/categories/': typeof CategoriesIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reports'
    | '/dashboard'
    | '/payments'
    | '/recipes'
    | '/stock'
    | '/tables'
    | '/transfers'
    | '/categories/$categoryId'
    | '/customers/$customerId'
    | '/products/$productId'
    | '/reports/inventory'
    | '/reports/payments'
    | '/reports/products'
    | '/reports/sales'
    | '/categories'
    | '/customers'
    | '/invoices'
    | '/orders'
    | '/products'
    | '/suppliers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reports'
    | '/dashboard'
    | '/payments'
    | '/recipes'
    | '/stock'
    | '/tables'
    | '/transfers'
    | '/categories/$categoryId'
    | '/customers/$customerId'
    | '/products/$productId'
    | '/reports/inventory'
    | '/reports/payments'
    | '/reports/products'
    | '/reports/sales'
    | '/categories'
    | '/customers'
    | '/invoices'
    | '/orders'
    | '/products'
    | '/suppliers'
  id:
    | '__root__'
    | '/'
    | '/reports'
    | '/dashboard'
    | '/payments'
    | '/recipes'
    | '/stock'
    | '/tables'
    | '/transfers'
    | '/categories/$categoryId'
    | '/customers/$customerId'
    | '/products/$productId'
    | '/reports/inventory'
    | '/reports/payments'
    | '/reports/products'
    | '/reports/sales'
    | '/categories/'
    | '/customers/'
    | '/invoices/'
    | '/orders/'
    | '/products/'
    | '/suppliers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReportsRouteRoute: typeof ReportsRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  PaymentsRoute: typeof PaymentsRoute
  RecipesRoute: typeof RecipesRoute
  StockRoute: typeof StockRoute
  TablesRoute: typeof TablesRoute
  TransfersRoute: typeof TransfersRoute
  CategoriesCategoryIdRoute: typeof CategoriesCategoryIdRoute
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/sales': {
      id: '/reports/sales'
      path: '/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof ReportsSalesRouteImport
      parentRoute: typeof ReportsRouteRoute
    }
    '/reports/products': {
      id: '/reports/products'
      path: '/products'
      fullPath: '/reports/products'
      preLoaderRoute: typeof ReportsProductsRouteImport
      parentRoute: typeof ReportsRouteRoute
    }
    '/reports/payments': {
      id: '/reports/payments'
      path: '/payments'
      fullPath: '/reports/payments'
      preLoaderRoute: typeof ReportsPaymentsRouteImport
      parentRoute: typeof ReportsRouteRoute
    }
    '/reports/inventory': {
      id: '/reports/inventory'
      path: '/inventory'
      fullPath: '/reports/inventory'
      preLoaderRoute: typeof ReportsInventoryRouteImport
      parentRoute: typeof ReportsRouteRoute
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categoryId': {
      id: '/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof CategoriesCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReportsRouteRouteChildren {
  ReportsInventoryRoute: typeof ReportsInventoryRoute
  ReportsPaymentsRoute: typeof ReportsPaymentsRoute
  ReportsProductsRoute: typeof ReportsProductsRoute
  ReportsSalesRoute: typeof ReportsSalesRoute
}

const ReportsRouteRouteChildren: ReportsRouteRouteChildren = {
  ReportsInventoryRoute: ReportsInventoryRoute,
  ReportsPaymentsRoute: ReportsPaymentsRoute,
  ReportsProductsRoute: ReportsProductsRoute,
  ReportsSalesRoute: ReportsSalesRoute,
}

const ReportsRouteRouteWithChildren = ReportsRouteRoute._addFileChildren(
  ReportsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReportsRouteRoute: ReportsRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  PaymentsRoute: PaymentsRoute,
  RecipesRoute: RecipesRoute,
  StockRoute: StockRoute,
  TablesRoute: TablesRoute,
  TransfersRoute: TransfersRoute,
  CategoriesCategoryIdRoute: CategoriesCategoryIdRoute,
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
