services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      NODE_ENV: production

  pos:
    build:
      context: .
      dockerfile: apps/pos-desktop/Dockerfile
    environment:
      NODE_ENV: production

  system-admin:
    build:
      context: .
      dockerfile: apps/system-admin/Dockerfile
    environment:
      NODE_ENV: production
