services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: installer # Use the installer stage which has dev deps
    command: pnpm --filter api dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/api/node_modules
    environment:
      NODE_ENV: development

  pos:
    build:
      context: .
      dockerfile: apps/pos-desktop/Dockerfile
      target: installer
    command: pnpm --filter pos-desktop dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/pos-desktop/node_modules
    environment:
      NODE_ENV: development

  system-admin:
    build:
      context: .
      dockerfile: apps/system-admin/Dockerfile
      target: installer
    command: pnpm --filter admin dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/system-admin/node_modules
    environment:
      NODE_ENV: development
