services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: pointverse-api
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
    networks:
      - pointverse-network

  pos:
    build:
      context: .
      dockerfile: apps/pos-desktop/Dockerfile
    container_name: pointverse-pos
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
    networks:
      - pointverse-network

  system-admin:
    build:
      context: .
      dockerfile: apps/system-admin/Dockerfile
    container_name: pointverse-admin
    ports:
      - "3002:3002"

    environment:
      PORT: 3002
    networks:
      - pointverse-network

networks:
  pointverse-network:
    driver: bridge
