packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - bcrypt
  - better-sqlite3
  - electron
  - electron-winstaller
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
  - ws
